name : Build & Sign Image for this repo

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE: ghcr.io/${{ github.repository }}:sha-${{ github.sha }}

jobs:
  build-sign:
  runs-on: ubuntu-latest

  permissions:
    contents: read
    id-token: write
    package: write

  steps:
    - uses: actions/checkout@v3

    - name: Login process (GHCR)
      run: echo "${{ secrets.G_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }}

    - name: Build docker image with demo app
      run: docker build -t ${{ env.IMAGE }} ./app

    - name: Push image
      run: docker push ${{ env.IMAGE }}

    - name: Install cosign
      run: |
        COSIGN_VERSION=v2.2.3
        curl -sSL https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-amd64 \
          -o cosign && chmod +x cosign && sudo mv cosign /usr/local/bin/
    
    - name: Sign image with cosign (keyless)
      run: cosign sign ${{ env.IMAGE }} --yes

