name : Build & Sign Image for this repo

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE: ghcr.io/${{ github.repository }}:sha-${{ github.sha }}

jobs:
  build-sign:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Login process (GHCR)
        run: echo "${{ secrets.G_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build docker image with demo app
        run: docker build -t ${{ env.IMAGE }} ./app

      - name: Push image
        run: docker push ${{ env.IMAGE }}

      - name: Install cosign
        run: |
          COSIGN_VERSION=v2.2.3
          curl -sSL https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-amd64 \
            -o cosign && chmod +x cosign && sudo mv cosign /usr/local/bin/
      
      - name: Sign image with cosign (keyless)
        run: cosign sign ${{ env.IMAGE }} --yes
        
      - name: Update Kubernetes Manifest
        run: |
          sed -i "s|image:.*|image: $IMAGE|" k8s/deployment.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image to $IMAGE"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git